obsidian:
  root_path: "/Users/kinshuk.chandra/lyf/scm/github/k2/apnotes2-ob/r"
hugo:
  root_path: "/Users/kinshuk.chandra/lyf/scm/github/k2/k5kc-content"
  content_dir: "content"
  manual_content_dir: "manual-content"
  posts_dir: ""
  posts_dir_list: ["cs/", "cs/problems/", "cs/algorithms", "cs/algorithms/search", "cs/algorithms/search/sorted", "cs/algorithms/graph", "cs/algorithms/graph/terminology", "cs/algorithms/graph/mst", "cs/algorithms/graph/color", "cs/algorithms/graph/vertex-cover", "cs/algorithms/graph/shortest-path", "cs/algorithms/techniques", "cs/algorithms/tree", "cs/problems/algorithms", "cs/problems/ood",  "cs/problems/java", "cs/problems/javascript", "cs/problems/bash", "cs/problems/shell", "cs/problems/pl", "cs/problems/sql", "cs/problems/database", "cs/problems/network", "cs/problems/network/web", "cs/problems/system-design", "cs/problems/concurrency", "cs/problems/pandas", "cs/ood", "cs/ood/core-pillars", "cs/ood/core-pillars/polymorphism", "cs/pl/", "cs/pl/java/", "cs/pl/javascript", "cs/pl/bash", "cs/pl/problems", "cs/pl/sql", "cs/network", "cs/network/web", "cs/system-design", "maths/", "maths/statistics", "maths/number-systems", "maths/arithmetic", "brain-teasers/", "gk/", "gk/algorithms", "cs/database", "cs/problems/backend-design", "cs/problems/db-design"]
  images_dir: "assets/images/obsidian"
  content_images_dir: "assets/images/obsidian"
  allowed_frontmatter_keys: []
